import os
import django
import sys
from datetime import timezone

# --- PASO 1: CONFIGURAR EL ENTORNO DE DJANGO ---
# (Esto le dice al script dónde encontrar tus modelos)
# Asegúrate de que 'config' sea el nombre de tu carpeta de settings
sys.path.append(os.path.abspath(os.path.dirname(__file__)))
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")
django.setup()

# --- PASO 2: IMPORTAR MODELOS ---
# (Ahora esto funciona, gracias al Paso 1)
from core.models import Tema, Curso, Pregunta
from django.db import transaction

# --- FUNCIÓN DE CARGA ---
def cargar_preguntas_excel():
    print('Iniciando carga de 50 preguntas de Excel...')

    try:
        with transaction.atomic():
            # --- 1. Obtener o Crear Tema ---
            tema_excel, tema_created = Tema.objects.get_or_create(
                nombre="Análisis de Datos"
            )
            if tema_created:
                print('Tema "Análisis de Datos" creado.')

            # --- 2. Obtener o Crear Curso ---
            curso_excel, curso_created = Curso.objects.get_or_create(
                nombre="Excel para Analistas (CDCV-P)",
                tema=tema_excel,
                defaults={'nivel': 2, 'descripcion': 'Curso completo de Excel para análisis de datos.', 'idioma': 'es'}
            )
            if curso_created:
                print(f'Curso "{curso_excel.nombre}" creado.')
            else:
                print(f'Curso "{curso_excel.nombre}" ya existía.')

            # --- 3. Definir las 50 Preguntas de Excel ---
            preguntas_excel_data = [
                # Nivel 1: Funciones Básicas y Lógica
                {"texto": "¿Qué función se utiliza para sumar un rango de celdas?", "opciones": {"A": {"texto": "PROMEDIO", "justificacion": "Incorrecto, PROMEDIO calcula la media."}, "B": {"texto": "SUMA", "justificacion": "Correcto, SUMA(A1:A10) suma todas las celdas en ese rango."}, "C": {"texto": "CONTAR", "justificacion": "Incorrecto, CONTAR cuenta el número de celdas."}}, "respuesta_correcta": "B"},
                {"texto": "Para calcular el valor promedio de un rango B2:B10, ¿qué fórmula usarías?", "opciones": {"A": {"texto": "=MEDIA(B2:B10)", "justificacion": "Incorrecto, MEDIA es de Google Sheets."}, "B": {"texto": "=SUMA(B2:B10)/CONTAR(B2:B10)", "justificacion": "Correcto, esta es la fórmula matemática, aunque =PROMEDIO es más directa."}, "C": {"texto": "=PROMEDIO(B2:B10)", "justificacion": "Correcto, esta es la función integrada de Excel."}}, "respuesta_correcta": "C"},
                {"texto": "¿Qué devuelve la fórmula =SI(A1 > 100, \"Alto\", \"Bajo\") si A1 es 50?", "opciones": {"A": {"texto": "Alto", "justificacion": "Incorrecto, 50 no es mayor que 100."}, "B": {"texto": "Bajo", "justificacion": "Correcto, 50 es menor que 100, por lo que se cumple la condición 'valor_si_falso'."}, "C": {"texto": "VERDADERO", "justificacion": "Incorrecto, la fórmula devuelve el texto especificado."}}, "respuesta_correcta": "B"},
                {"texto": "¿Qué tecla se usa para fijar una referencia de celda (ej. $A$1)?", "opciones": {"A": {"texto": "F2", "justificacion": "Incorrecto, F2 se usa para editar el contenido de una celda."}, "B": {"texto": "F4", "justificacion": "Correcto, al editar una fórmula, F4 alterna entre referencias relativas, absolutas y mixtas."}, "C": {"texto": "F9", "justificacion": "Incorrecto, F9 recalcula la hoja."}}, "respuesta_correcta": "B"},
                {"texto": "La función MAX() se utiliza para...", "opciones": {"A": {"texto": "Encontrar el texto más largo.", "justificacion": "Incorrecto."}, "B": {"texto": "Encontrar el valor numérico más alto en un rango.", "justificacion": "Correcto."}, "C": {"texto": "Maximizar la ventana de Excel.", "justificacion": "Incorrecto."}}, "respuesta_correcta": "B"},
                {"texto": "La función MIN() se utiliza para...", "opciones": {"A": {"texto": "Minimizar la ventana de Excel.", "justificacion": "Incorrecto."}, "B": {"texto": "Encontrar el valor numérico más bajo en un rango.", "justificacion": "Correcto."}, "C": {"texto": "Encontrar el texto más corto.", "justificacion": "Incorrecto."}}, "respuesta_correcta": "B"},
                {"texto": "¿Qué hace la función CONTAR(A1:A100)?", "opciones": {"A": {"texto": "Cuenta todas las celdas en el rango.", "justificacion": "Incorrecto, solo cuenta celdas con números."}, "B": {"texto": "Suma los valores del rango.", "justificacion": "Incorrecto, eso es SUMA()."}, "C": {"texto": "Cuenta cuántas celdas en el rango contienen números.", "justificacion": "Correcto."}}, "respuesta_correcta": "C"},
                {"texto": "¿Qué hace la función CONTARA(A1:A100)?", "opciones": {"A": {"texto": "Cuenta solo celdas con texto.", "justificacion": "Incorrecto."}, "B": {"texto": "Cuenta cuántas celdas en el rango NO están vacías.", "justificacion": "Correcto, cuenta números, texto, errores, etc. Solo ignora las vacías."}, "C": {"texto": "Cuenta solo celdas vacías.", "justificacion": "Incorrecto, eso es CONTAR.BLANCO()."}}, "respuesta_correcta": "B"},
                {"texto": "¿Qué devuelve =Y(A1>5, A1<10) si A1 es 8?", "opciones": {"A": {"texto": "VERDADERO", "justificacion": "Correcto, 8 es mayor que 5 Y 8 es menor que 10. Ambas son verdaderas."}, "B": {"texto": "FALSO", "justificacion": "Incorrecto, ambas condiciones se cumplen."}, "C": {"texto": "8", "justificacion": "Incorrecto, las funciones lógicas devuelven VERDADERO o FALSO."}}, "respuesta_correcta": "A"},
                {"texto": "¿Qué devuelve =O(A1>5, A1<3) si A1 es 8?", "opciones": {"A": {"texto": "VERDADERO", "justificacion": "Correcto, 8 es mayor que 5. Con la función O(), solo se necesita que una condición sea verdadera."}, "B": {"texto": "FALSO", "justificacion": "Incorrecto, la primera condición (A1>5) es verdadera."}, "C": {"texto": "Error", "justificacion": "Incorrecto."}}, "respuesta_correcta": "A"},
    
                # Nivel 2: Funciones de Búsqueda y Referencia
                {"texto": "¿Cuál es el propósito principal de BUSCARV (VLOOKUP)?", "opciones": {"A": {"texto": "Buscar un valor en la primera fila de una tabla.", "justificacion": "Incorrecto, eso es BUSCARH (HLOOKUP)."}, "B": {"texto": "Buscar un valor en la primera columna de una tabla y devolver un valor de una columna a la derecha.", "justificacion": "Correcto."}, "C": {"texto": "Sumar valores basados en un criterio.", "justificacion": "Incorrecto, eso es SUMAR.SI."}}, "respuesta_correcta": "B"},
                {"texto": "En BUSCARV(A2, B:D, 3, FALSO), ¿qué significa el '3'?", "opciones": {"A": {"texto": "Busca el valor en la tercera fila.", "justificacion": "Incorrecto."}, "B": {"texto": "El valor a buscar 'A2' está en la columna 3.", "justificacion": "Incorrecto."}, "C": {"texto": "Devuelve el valor de la tercera columna del rango (B:D).", "justificacion": "Correcto. Si B es la col 1, C es la 2, D es la 3."}}, "respuesta_correcta": "C"},
                {"texto": "En BUSCARV(A2, B:D, 3, FALSO), ¿qué significa 'FALSO'?", "opciones": {"A": {"texto": "Que la búsqueda debe ser una coincidencia exacta.", "justificacion": "Correcto. Si no encuentra el valor exacto, devuelve #N/A."}, "B": {"texto": "Que la búsqueda debe ser una coincidencia aproximada.", "justificacion": "Incorrecto, eso es VERDADERO."}, "C": {"texto": "Que la tabla no está ordenada.", "justificacion": "Incorrecto."}}, "respuesta_correcta": "A"},
                {"texto": "¿Qué función es considerada la sucesora moderna y más flexible de BUSCARV/BUSCARH?", "opciones": {"A": {"texto": "INDICE (INDEX) y COINCIDIR (MATCH)", "justificacion": "Correcto, la combinación de INDICE y COINCIDIR es más potente: busca en cualquier dirección (izquierda/derecha) y es más eficiente."}, "B": {"texto": "BUSCARX (XLOOKUP)", "justificacion": "Correcto, BUSCARX (disponible en Excel 365 y 2021) reemplaza a BUSCARV, BUSCARH e INDICE/COINCIDIR con una sola función más simple."}, "C": {"texto": "SUMAR.SI.CONJUNTO", "justificacion": "Incorrecto."}}, "respuesta_correcta": "B"},
                {"texto": "La función COINCIDIR(A1, C:C, 0) devuelve...", "opciones": {"A": {"texto": "El valor de la celda.", "justificacion": "Incorrecto."}, "B": {"texto": "El número de fila (posición relativa) donde A1 se encuentra en la columna C.", "justificacion": "Correcto. El '0' indica coincidencia exacta."}, "C": {"texto": "VERDADERO o FALSO.", "justificacion": "Incorrecto."}}, "respuesta_correcta": "B"},
                {"texto": "¿Qué hace la función INDICE(A:C, 5, 2)?", "opciones": {"A": {"texto": "Busca el valor de la celda B5.", "justificacion": "Correcto. Devuelve el valor en la intersección de la Fila 5 y la Columna 2 (Columna B) del rango A:C."}, "B": {"texto": "Busca el valor de la celda C5.", "justificacion": "Incorrecto, esa sería la columna 3."}, "C": {"texto": "Busca el valor de la celda A2.", "justificacion": "Incorrecto."}}, "respuesta_correcta": "A"},
                {"texto": "Si quieres buscar a la izquierda con BUSCARV, ¿qué debes hacer?", "opciones": {"A": {"texto": "Usar un número de columna negativo.", "justificacion": "Incorrecto, BUSCARV no puede hacer esto."}, "B": {"texto": "Usar INDICE y COINCIDIR.", "justificacion": "Correcto, esta es la forma clásica de superar la limitación de BUSCARV."}, "C": {"texto": "Cambiar el orden de las columnas.", "justificacion": "Correcto, aunque esto es una solución estructural, no una solución de fórmula."}}, "respuesta_correcta": "B"},
                {"texto": "¿Cuál es la principal ventaja de BUSCARX sobre BUSCARV?", "opciones": {"A": {"texto": "Es más rápida.", "justificacion": "No necesariamente su principal ventaja."}, "B": {"texto": "Usa coincidencia exacta por defecto y puede buscar a la izquierda.", "justificacion": "Correcto, BUSCARX es más intuitiva (FALSO es el defecto) y potente (busca en cualquier dirección)."}, "C": {"texto": "Es más antigua y compatible.", "justificacion": "Incorrecto, es más nueva y menos compatible con versiones antiguas."}}, "respuesta_correcta": "B"},
                {"texto": "¿Qué hace la función TRANSPONER?", "opciones": {"A": {"texto": "Invierte el orden de las filas.", "justificacion": "Incorrecto."}, "B": {"texto": "Convierte un rango de filas en columnas, o de columnas en filas.", "justificacion": "Correcto. Es una función de matriz."}, "C": {"texto": "Traduce el texto de la celda.", "justificacion": "Incorrecto."}}, "respuesta_correcta": "B"},
                {"texto": "¿Qué función te permite obtener parte de un texto? (ej. 'Excel' de 'Microsoft Excel')", "opciones": {"A": {"texto": "EXTRAE (MID)", "justificacion": "Correcto, EXTRAE(texto, pos_inicial, num_caracteres) hace esto."}, "B": {"texto": "DERECHA (RIGHT)", "justificacion": "Correcto, DERECHA(texto, 5) también daría 'Excel'."}, "C": {"texto": "IZQUIERDA (LEFT)", "justificacion": "Incorrecto, esto daría 'Microsoft'."}}, "respuesta_correcta": "A"},
    
                # Nivel 3: Tablas Dinámicas (Pivot Tables)
                {"texto": "¿Cuál es el propósito principal de una Tabla Dinámica?", "opciones": {"A": {"texto": "Crear gráficos bonitos.", "justificacion": "Incorrecto, aunque se pueden basar en ellas, no es su propósito principal."}, "B": {"texto": "Resumir, agrupar y analizar grandes cantidades de datos de forma interactiva.", "justificacion": "Correcto. Permiten arrastrar y soltar campos para ver resúmenes (SUMA, PROMEDIO, CONTAR)."}, "C": {"texto": "Buscar un valor específico.", "justificacion": "Incorrecto, eso es BUSCARV."}}, "respuesta_correcta": "B"},
                {"texto": "En una Tabla Dinámica, ¿dónde arrastrarías un campo de 'Ventas ($)' para ver el total?", "opciones": {"A": {"texto": "Al área de FILAS.", "justificacion": "Incorrecto, esto mostraría cada valor de venta único como una fila."}, "B": {"texto": "Al área de VALORES.", "justificacion": "Correcto. El área de Valores es para campos numéricos que se desean calcular (SUMA, PROMEDIO, etc.)."}, "C": {"texto": "Al área de FILTROS.", "justificacion": "Incorrecto."}}, "respuesta_correcta": "B"},
                {"texto": "En una Tabla Dinámica, ¿dónde arrastrarías un campo de 'Región' para ver las ventas por región?", "opciones": {"A": {"texto": "Al área de FILAS (o COLUMNAS).", "justificacion": "Correcto. Esto agrupa los datos por cada región única."}, "B": {"texto": "Al área de VALORES.", "justificacion": "Incorrecto, Excel intentaría 'Contar' las regiones, no sumar valores."}, "C": {"texto": "Solo se puede en FILTROS.", "justificacion": "Incorrecto."}}, "respuesta_correcta": "A"},
                {"texto": "¿Qué es 'Actualizar' (Refresh) en una Tabla Dinámica?", "opciones": {"A": {"texto": "Cambia el diseño visual de la tabla.", "justificacion": "Incorrecto."}, "B": {"texto": "Vuelve a calcular la tabla basado en los datos de origen (si estos cambiaron).", "justificacion": "Correcto. Las Tablas Dinámicas no se actualizan solas; hay que hacerlo manualmente."}, "C": {"texto": "Deshace el último cambio.", "justificacion": "Incorrecto."}}, "respuesta_correcta": "B"},
                {"texto": "¿Qué es un 'Slicer' (Segmentación de datos) en una Tabla Dinámica?", "opciones": {"A": {"texto": "Un tipo de gráfico.", "justificacion": "Incorrecto."}, "B": {"texto": "Un filtro visual interactivo (un botón) que permite filtrar la Tabla Dinámica.", "justificacion": "Correcto. Es más amigable que usar el menú de filtros."}, "C": {"texto": "Una forma de cortar los datos por la mitad.", "justificacion": "Incorrecto."}}, "respuesta_correcta": "B"},
                {"texto": "Si los datos de origen de tu Tabla Dinámica aumentan (más filas), ¿qué debes hacer?", "opciones": {"A": {"texto": "Nada, solo 'Actualizar'.", "justificacion": "Incorrecto, 'Actualizar' no detecta nuevas filas fuera del rango original."}, "B": {"texto": "Borrar la tabla y crearla de nuevo.", "justificacion": "Funciona, pero es ineficiente."}, "C": {"texto": "Ir a 'Cambiar origen de datos' o usar una 'Tabla de Excel' (Ctrl+T) como origen.", "justificacion": "Correcto. Usar una Tabla (Ctrl+T) como origen es la mejor práctica, ya que se expande automáticamente."}}, "respuesta_correcta": "C"},
                {"texto": "¿Qué hace la opción 'Agrupar' en un campo de fecha en una Tabla Dinámica?", "opciones": {"A": {"texto": "Agrupa automáticamente las fechas por Meses, Trimestres y Años.", "justificacion": "Correcto. Es una de las funciones más potentes de las Tablas Dinámicas."}, "B": {"texto": "Elimina las fechas.", "justificacion": "Incorrecto."}, "C": {"texto": "Solo funciona si las fechas son texto.", "justificacion": "Incorrecto, deben ser fechas válidas."}}, "respuesta_correcta": "A"},
                {"texto": "¿Qué es un 'Campo Calculado' en una Tabla Dinámica?", "opciones": {"A": {"texto": "Una celda donde escribes una fórmula fuera de la tabla.", "justificacion": "Incorrecto."}, "B": {"texto": "Un nuevo campo (columna) dentro de la Tabla Dinámica que creas usando una fórmula basada en otros campos.", "justificacion": "Correcto. Ej. un campo 'Comisión' = 'Ventas' * 0.10."}, "C": {"texto": "El total general.", "justificacion": "Incorrecto."}}, "respuesta_correcta": "B"},
                {"texto": "¿Qué formato de datos es el ideal para crear una Tabla Dinámica?", "opciones": {"A": {"texto": "Un reporte con subtotales y celdas combinadas.", "justificacion": "Incorrecto, esto es lo peor para una Tabla Dinámica."}, "B": {"texto": "Datos 'planos' o 'tabulares' (cada fila es un registro, cada columna es un campo, sin celdas combinadas).", "justificacion": "Correcto. La base de datos debe estar normalizada."}, "C": {"texto": "Datos en horizontal.", "justificacion": "Incorrecto."}}, "respuesta_correcta": "B"},
                {"texto": "¿Para qué sirve el área de 'COLUMNAS' en una Tabla Dinámica?", "opciones": {"A": {"texto": "Para crear una cabecera de columna por cada valor único del campo.", "justificacion": "Correcto. Similar a FILAS, pero crea una tabla de doble entrada (matriz)."}, "B": {"texto": "Es obligatorio usarla.", "justificacion": "Incorrecto."}, "C": {"texto": "Solo para poner fechas.", "justificacion": "Incorrecto."}}, "respuesta_correcta": "A"},
    
                # Nivel 4: Funciones Avanzadas y Condicionales
                {"texto": "¿Qué hace la función SUMAR.SI?", "opciones": {"A": {"texto": "Suma un rango de celdas si se cumplen múltiples condiciones.", "justificacion": "Incorrecto, eso es SUMAR.SI.CONJUNTO."}, "B": {"texto": "Suma un rango de celdas si se cumple UNA condición.", "justificacion": "Correcto. Ej. =SUMAR.SI(A:A, \"Fruta\", B:B) suma las ventas (B:B) solo si la categoría (A:A) es \"Fruta\"."}, "C": {"texto": "Suma todas las celdas que contienen \"SI\".", "justificacion": "Incorrecto."}}, "respuesta_correcta": "B"},
                {"texto": "¿Qué hace la función SUMAR.SI.CONJUNTO?", "opciones": {"A": {"texto": "Suma un rango de celdas si se cumple CUALQUIERA de varias condiciones.", "justificacion": "Incorrecto."}, "B": {"texto": "Suma un rango de celdas si se cumplen TODAS las condiciones especificadas.", "justificacion": "Correcto. Es más potente que SUMAR.SI."}, "C": {"texto": "Suma varias hojas de cálculo.", "justificacion": "Incorrecto."}}, "respuesta_correcta": "B"},
                {"texto": "La función CONTAR.SI(A:A, \">10\") hará lo siguiente:", "opciones": {"A": {"texto": "Contará cuántas celdas en la columna A son mayores que 10.", "justificacion": "Correcto."}, "B": {"texto": "Sumará las celdas mayores que 10.", "justificacion": "Incorrecto, eso es SUMAR.SI."}, "C": {"texto": "Devolverá un error por el \">10\".", "justificacion": "Incorrecto, esa es la sintaxis correcta para el criterio."}}, "respuesta_correcta": "A"},
                {"texto": "¿Qué hace la función SI.ERROR (IFERROR)?", "opciones": {"A": {"texto": "Corrige el error en una fórmula.", "justificacion": "Incorrecto, no lo corrige, lo gestiona."}, "B": {"texto": "Devuelve un valor específico (ej. 0 o \"Error\") si la fórmula evaluada da un error (ej. #N/A, #DIV/0!).", "justificacion": "Correcto. Ej. =SI.ERROR(A1/B1, 0) devuelve 0 si B1 es cero."}, "C": {"texto": "Muestra un mensaje de alerta.", "justificacion": "Incorrecto."}}, "respuesta_correcta": "B"},
                {"texto": "¿Qué hace la función CONCATENAR (o el operador &)?", "opciones": {"A": {"texto": "Suma números.", "justificacion": "Incorrecto."}, "B": {"texto": "Une dos o más cadenas de texto en una sola.", "justificacion": "Correcto. Ej. =CONCATENAR(A1, \" \", B1) o =A1 & \" \" & B1."}, "C": {"texto": "Divide el texto.", "justificacion": "Incorrecto, eso es Texto en Columnas."}}, "respuesta_correcta": "B"},
                {"texto": "¿Para qué sirve el 'Formato Condicional'?", "opciones": {"A": {"texto": "Para cambiar el formato de una celda (ej. color de fondo, fuente) basado en una regla o condición.", "justificacion": "Correcto. Ej. poner en rojo todas las celdas con valores negativos."}, "B": {"texto": "Para bloquear una celda.", "justificacion": "Incorrecto."}, "C": {"texto": "Para crear una fórmula SI.", "justificacion": "Incorrecto."}}, "respuesta_correcta": "A"},
                {"texto": "¿Qué es la 'Validación de Datos'?", "opciones": {"A": {"texto": "Una forma de crear una lista desplegable en una celda.", "justificacion": "Correcto, es uno de sus usos más comunes."}, "B": {"texto": "Restringir el tipo de datos que se puede ingresar en una celda (ej. solo números enteros, solo fechas).", "justificacion": "Correcto, es su propósito principal."}, "C": {"texto": "Ambas A y B son correctas.", "justificacion": "Correcto. La validación de datos controla la entrada del usuario."}}, "respuesta_correcta": "C"},
                {"texto": "¿Qué hace la función HOY()?", "opciones": {"A": {"texto": "Devuelve la fecha y hora actuales.", "justificacion": "Incorrecto, eso es AHORA()."}, "B": {"texto": "Devuelve solo la fecha actual.", "justificacion": "Correcto. Es una función volátil (se actualiza cada vez que se recalcula la hoja)."}, "C": {"texto": "Inserta la fecha de hoy como texto estático.", "justificacion": "Incorrecto."}}, "respuesta_correcta": "B"},
                {"texto": "¿Qué hace la función AHORA()?", "opciones": {"A": {"texto": "Devuelve solo la fecha actual.", "justificacion": "Incorrecto, eso es HOY()."}, "B": {"texto": "Devuelve la fecha y la hora actuales.", "justificacion": "Correcto."}, "C": {"texto": "Pregunta la hora.", "justificacion": "Incorrecto."}}, "respuesta_correcta": "B"},
                {"texto": "¿Qué hace la herramienta 'Texto en Columnas'?", "opciones": {"A": {"texto": "Une varias columnas de texto.", "justificacion": "Incorrecto, eso es CONCATENAR."}, "B": {"texto": "Divide el contenido de una columna de texto en múltiples columnas basado en un delimitador (ej. coma, espacio) o ancho fijo.", "justificacion": "Correcto."}, "C": {"texto": "Cambia la orientación del texto a vertical.", "justificacion": "Incorrecto."}}, "respuesta_correcta": "B"},
    
                # Nivel 5: Análisis y Escenarios
                {"texto": "¿Qué es la herramienta 'Buscar Objetivo' (Goal Seek)?", "opciones": {"A": {"texto": "Una herramienta que ajusta el valor de una celda (celda cambiante) para alcanzar un resultado específico en otra celda (celda objetivo).", "justificacion": "Correcto. Ej. ¿Qué tasa de interés necesito (celda cambiante) para que mi pago mensual (celda objetivo) sea $500?"}, "B": {"texto": "Una herramienta de búsqueda de texto.", "justificacion": "Incorrecto."}, "C": {"texto": "Una forma de crear un escenario.", "justificacion": "Incorrecto, aunque relacionado."}}, "respuesta_correcta": "A"},
                {"texto": "¿Para qué sirve el 'Administrador de Escenarios'?", "opciones": {"A": {"texto": "Para comparar los resultados de múltiples conjuntos de variables de entrada.", "justificacion": "Correcto. Ej. comparar la Ganancia Neta en un escenario 'Optimista' (Ventas=1000), 'Pesimista' (Ventas=500) y 'Base' (Ventas=750)."}, "B": {"texto": "Para gestionar las hojas del libro.", "justificacion": "Incorrecto."}, "C": {"texto": "Para administrar los usuarios.", "justificacion": "Incorrecto."}}, "respuesta_correcta": "A"},
                {"texto": "¿Qué es 'Solver'?", "opciones": {"A": {"texto": "Una versión más simple de Buscar Objetivo.", "justificacion": "Incorrecto, es mucho más avanzada."}, "B": {"texto": "Un complemento (add-in) para optimización y programación lineal.", "justificacion": "Correcto. Puede maximizar o minimizar una celda objetivo cambiando múltiples celdas y sujeto a múltiples restricciones."}, "C": {"texto": "Una herramienta para solucionar errores #N/A.", "justificacion": "Incorrecto."}}, "respuesta_correcta": "B"},
                {"texto": "¿Qué es una 'Tabla de Datos' (Data Table) en análisis de escenarios?", "opciones": {"A": {"texto": "Una Tabla de Excel (Ctrl+T).", "justificacion": "Incorrecto, es un nombre confuso pero son diferentes."}, "B": {"texto": "Una herramienta que calcula los resultados de una fórmula al variar una o dos variables.", "justificacion": "Correcto. Ej. mostrar cómo cambia el pago del préstamo al variar la tasa de interés Y el plazo."}, "C": {"texto": "Una Tabla Dinámica.", "justificacion": "Incorrecto."}}, "respuesta_correcta": "B"},
                {"texto": "¿Cómo se accede a la herramienta 'Solver'?", "opciones": {"A": {"texto": "Está en la pestaña 'Datos' por defecto.", "justificacion": "Incorrecto, debe activarse primero."}, "B": {"texto": "Debe activarse desde 'Archivo' > 'Opciones' > 'Complementos' > 'Complementos de Excel'.", "justificacion": "Correcto."}, "C": {"texto": "Se debe descargar de internet.", "justificacion": "Incorrecto."}}, "respuesta_correcta": "B"},
                {"texto": "¿Cuál es la diferencia principal entre 'Buscar Objetivo' y 'Solver'?", "opciones": {"A": {"texto": "Buscar Objetivo maneja 1 variable; Solver maneja múltiples variables y restricciones.", "justificacion": "Correcto. Solver es la herramienta de optimización completa."}, "B": {"texto": "Solver es gratis y Buscar Objetivo es pagado.", "justificacion": "Incorrecto, ambos vienen con Excel."}, "C": {"texto": "No hay diferencia.", "justificacion": "Incorrecto."}}, "respuesta_correcta": "A"},
                {"texto": "La función PAGO() se utiliza para...", "opciones": {"A": {"texto": "Calcular el pago de un préstamo (ej. hipoteca) basado en una tasa de interés, número de períodos y monto constante.", "justificacion": "Correcto."}, "B": {"texto": "Registrar un pago en una base de datos.", "justificacion": "Incorrecto."}, "C": {"texto": "Abrir PayPal.", "justificacion": "Incorrecto."}}, "respuesta_correcta": "A"},
                {"texto": "¿Qué es un Gráfico de Cascada (Waterfall Chart)?", "opciones": {"A": {"texto": "Un gráfico que muestra el flujo de agua.", "justificacion": "Incorrecto."}, "B": {"texto": "Un gráfico que muestra cómo un valor inicial es afectado por una serie de valores positivos y negativos (ej. Ingresos - Costos = Ganancia).", "justificacion": "Correcto. Es muy usado en finanzas."}, "C": {"texto": "Un gráfico de burbujas.", "justificacion": "Incorrecto."}}, "respuesta_correcta": "B"},
                {"texto": "¿Para qué sirve la herramienta 'Quitar Duplicados'?", "opciones": {"A": {"texto": "Para eliminar filas de una tabla que son idénticas (o duplicadas en columnas clave).", "justificacion": "Correcto."}, "B": {"texto": "Para encontrar errores.", "justificacion": "Incorrecto."}, "C": {"texto": "Para duplicar una hoja.", "justificacion": "Incorrecto."}}, "respuesta_correcta": "A"},
                {"texto": "¿Qué es Power Query (Obtener y Transformar)?", "opciones": {"A": {"texto": "Una herramienta de gráficos.", "justificacion": "Incorrecto."}, "B": {"texto": "Un motor de ETL (Extraer, Transformar, Cargar) para conectar, limpiar y dar forma a datos de múltiples fuentes antes de cargarlos a Excel.", "justificacion": "Correcto. Es la base de la inteligencia de negocios moderna en Excel."}, "C": {"texto": "Una versión de Power Point.", "justificacion": "Incorrecto."}}, "respuesta_correcta": "B"}
            ]

            # --- 4. Crear las Preguntas (de forma segura) ---
            preguntas_creadas = 0
            preguntas_existentes = 0
            for data in preguntas_excel_data:
                # Usamos get_or_create para que el script sea re-ejecutable
                # Busca por 'curso' y 'texto'
                pregunta, created = Pregunta.objects.get_or_create(
                    curso=curso_excel,
                    texto=data['texto'],
                    defaults={
                        'opciones': data['opciones'],
                        'respuesta_correcta': data['respuesta_correcta'],
                        'nivel': 2,
                        'idioma': 'es'
                    }
                )
                
                if created:
                    preguntas_creadas += 1
                else:
                    preguntas_existentes += 1
            
            print(f'{preguntas_creadas} nuevas preguntas de Excel fueron creadas.')
            if preguntas_existentes > 0:
                print(f'{preguntas_existentes} preguntas de Excel ya existían (no se duplicaron).')

    except Exception as e:
        print(f"ERROR: No se pudo cargar la base de datos. {e}")

# --- PASO 3: EJECUTAR LA FUNCIÓN ---
if __name__ == "__main__":
    cargar_preguntas_excel()