# Generated by Django 5.2.8 on 2025-12-27 23:30

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('precio_usd', models.DecimalField(decimal_places=2, default=29.0, max_digits=6)),
                ('nivel', models.IntegerField(default=1)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('idioma', models.CharField(default='es', max_length=10)),
                ('activo', models.BooleanField(default=False, verbose_name='¿Visible en Catálogo?')),
                ('cantidad_preguntas', models.PositiveIntegerField(default=10, verbose_name='Preguntas por Examen')),
                ('score', models.IntegerField(default=0, help_text='Puntaje de calidad (0-30)')),
                ('status', models.CharField(default='PENDIENTE', help_text='Estado de curación', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estructura_examen', models.JSONField(blank=True, default=dict, help_text="JSON que define la 'receta' del examen.", null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MicroCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('definicion_atomica', models.TextField(help_text="Define el límite exacto. Ej: 'Solo suma de celdas contiguas, no rangos'.")),
                ('criterio_exito', models.TextField(help_text="Regla binaria para la IA. Ej: 'El usuario llega al resultado sin usar mouse'.")),
                ('prompt_validacion', models.TextField(blank=True, help_text='Instrucción base que se enviará a Gemini para evaluar esta competencia.', null=True)),
                ('icono', models.CharField(default='🏆', help_text='Emoji o URL', max_length=50)),
                ('embedding_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('idioma', models.CharField(default='es', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preguntas_set', models.JSONField(default=list, help_text='Lista de IDs de Pregunta que se usaron')),
                ('respuestas_usuario', models.JSONField(blank=True, default=dict, help_text='Respuestas enviadas por el usuario', null=True)),
                ('puntaje', models.FloatField(default=0)),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='certificados/')),
                ('codigo_qr', models.FileField(blank=True, null=True, upload_to='codigos_qr/')),
                ('codigo_verificacion', models.UUIDField(unique=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curso')),
                ('examen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.examen')),
            ],
        ),
        migrations.CreateModel(
            name='CursoMicroCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden en que se enseña (1, 2, 3...)')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curso')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.microcompetencia')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('curso', 'competencia')},
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='micro_competencias',
            field=models.ManyToManyField(help_text='Las competencias específicas que componen este curso.', related_name='cursos', through='core.CursoMicroCompetencia', to='core.microcompetencia'),
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('opciones', models.JSONField()),
                ('respuesta_correcta', models.CharField(max_length=1)),
                ('justificacion', models.TextField(default='Respuesta basada en la definición de la competencia.', help_text='Explicación que se muestra al alumno si falla.')),
                ('dificultad', models.IntegerField(default=1, help_text='Nivel de dificultad objetivo (1=Básico, 5=Experto)')),
                ('nivel', models.IntegerField(default=1, help_text="[Legacy] Usar 'dificultad' en su lugar.")),
                ('idioma', models.CharField(default='es', max_length=10)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.curso')),
                ('micro_competencia', models.ForeignKey(blank=True, help_text='La competencia exacta que valida esta pregunta.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preguntas_banco', to='core.microcompetencia')),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('micro_competencias', models.ManyToManyField(blank=True, related_name='temas', to='core.microcompetencia')),
                ('parent', models.ForeignKey(blank=True, help_text='Usado para crear subtemas o taxonomía.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtemas', to='core.tema')),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaTema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevancia_score', models.FloatField(default=1.0, help_text='Puntaje (0.0 a 1.0) asignado por IA sobre la relevancia.')),
                ('revisado_por_agente', models.BooleanField(default=False, help_text='Marcado como True si un agente de IA ha validado esta relación.')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pregunta')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tema')),
            ],
            options={
                'verbose_name': 'Relación Pregunta-Tema',
                'verbose_name_plural': 'Relaciones Preguntas-Temas',
                'unique_together': {('pregunta', 'tema')},
            },
        ),
        migrations.AddField(
            model_name='pregunta',
            name='temas',
            field=models.ManyToManyField(help_text='Etiquetas reutilizables (Temas/Subtemas) para esta pregunta.', related_name='preguntas', through='core.PreguntaTema', to='core.tema'),
        ),
        migrations.AddField(
            model_name='curso',
            name='temas',
            field=models.ManyToManyField(help_text='Los módulos o temas que componen este curso.', related_name='cursos', to='core.tema'),
        ),
        migrations.CreateModel(
            name='InsigniaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_obtenida', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insignias', to=settings.AUTH_USER_MODEL)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.microcompetencia')),
            ],
            options={
                'verbose_name': 'Insignia Ganada',
                'verbose_name_plural': 'Insignias Ganadas',
                'unique_together': {('usuario', 'competencia')},
            },
        ),
        migrations.CreateModel(
            name='ProgresoCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('LOCKED', 'Bloqueado'), ('PENDING', 'Pendiente'), ('FAILED', 'Requiere Estudio'), ('VERIFIED', 'Validado')], default='LOCKED', max_length=20)),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.microcompetencia')),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.curso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'competencia', 'curso')},
            },
        ),
    ]
