# Generated by Django 5.2.4 on 2025-12-26 02:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='tema',
        ),
        migrations.RemoveField(
            model_name='microcompetencia',
            name='tema',
        ),
        migrations.AddField(
            model_name='curso',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='precio_usd',
            field=models.DecimalField(decimal_places=2, default=29.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='curso',
            name='temas',
            field=models.ManyToManyField(help_text='Los módulos o temas que componen este curso.', related_name='cursos', to='core.tema'),
        ),
        migrations.AddField(
            model_name='curso',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='microcompetencia',
            name='icono',
            field=models.CharField(default='🏆', help_text='Emoji o URL', max_length=50),
        ),
        migrations.AddField(
            model_name='tema',
            name='micro_competencias',
            field=models.ManyToManyField(blank=True, related_name='temas', to='core.microcompetencia'),
        ),
        migrations.AddField(
            model_name='tema',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
