# Generated by Django 5.2.8 on 2025-11-10 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='curso',
        ),
        migrations.AddField(
            model_name='curso',
            name='estructura_examen',
            field=models.JSONField(blank=True, default=dict, help_text="JSON que define la 'receta' del examen. Ej: {'total': 10, 'reglas': [{'tema_id': 1, 'dificultad': [1,2], 'cantidad': 5}, ...]}", null=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='dificultad',
            field=models.IntegerField(default=1, help_text='Nivel de dificultad objetivo (1=Básico, 5=Experto)'),
        ),
        migrations.AddField(
            model_name='tema',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Usado para crear subtemas o taxonomía.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtemas', to='core.tema'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='tema',
            field=models.ForeignKey(blank=True, help_text='El tema principal o categoría de este curso.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tema'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='nivel',
            field=models.IntegerField(default=1, help_text="[Legacy] Usar 'dificultad' en su lugar."),
        ),
        migrations.CreateModel(
            name='PreguntaTema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevancia_score', models.FloatField(default=1.0, help_text='Puntaje (0.0 a 1.0) asignado por un agente de IA sobre la relevancia de esta pregunta para este tema.')),
                ('revisado_por_agente', models.BooleanField(default=False, help_text='Marcado como True si un agente de IA de revisión ha validado esta relación.')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pregunta')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tema')),
            ],
            options={
                'verbose_name': 'Relación Pregunta-Tema',
                'verbose_name_plural': 'Relaciones Preguntas-Temas',
                'unique_together': {('pregunta', 'tema')},
            },
        ),
        migrations.AddField(
            model_name='pregunta',
            name='temas',
            field=models.ManyToManyField(help_text='Etiquetas reutilizables (Temas/Subtemas) para esta pregunta.', related_name='preguntas', through='core.PreguntaTema', to='core.tema'),
        ),
    ]
