# Generated by Django 5.2.4 on 2026-01-05 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilMicroCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_actual', models.FloatField(default=1.0)),
                ('intentos_totales', models.PositiveIntegerField(default=0)),
                ('aciertos', models.PositiveIntegerField(default=0)),
                ('racha_actual', models.IntegerField(default=0)),
                ('ultima_practica', models.DateTimeField(auto_now=True)),
                ('micro_competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.microcompetencia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Habilidad (User)',
                'unique_together': {('usuario', 'micro_competencia')},
            },
        ),
    ]
