# Generated by Django 5.2.4 on 2025-12-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_curso_tema_remove_microcompetencia_tema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='justificacion',
            field=models.TextField(default='Respuesta basada en la definición de la competencia.', help_text='Explicación que se muestra al alumno si falla.'),
        ),
    ]
