# Generated by Django 5.2.4 on 2026-01-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_perfilmicrocompetencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preguntatema',
            options={},
        ),
        migrations.RemoveField(
            model_name='tema',
            name='micro_competencias',
        ),
        migrations.RemoveField(
            model_name='tema',
            name='parent',
        ),
        migrations.AddField(
            model_name='microcompetencia',
            name='temas',
            field=models.ManyToManyField(help_text='Temas macro a los que pertenece esta habilidad (Ej: Excel).', related_name='competencias', to='core.tema'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='estructura_examen',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='micro_competencias',
            field=models.ManyToManyField(related_name='cursos', through='core.CursoMicroCompetencia', to='core.microcompetencia'),
        ),
        migrations.AlterField(
            model_name='cursomicrocompetencia',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Orden en que se enseña'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='dificultad',
            field=models.IntegerField(default=1, help_text='1=Básico, 5=Experto'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='nivel',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='temas',
            field=models.ManyToManyField(help_text='Etiquetas reutilizables asignadas por la IA.', related_name='preguntas', through='core.PreguntaTema', to='core.tema'),
        ),
        migrations.AlterField(
            model_name='preguntatema',
            name='relevancia_score',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='preguntatema',
            name='revisado_por_agente',
            field=models.BooleanField(default=False),
        ),
    ]
