# Generated by Django 5.2.4 on 2025-12-16 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_pregunta_curso_curso_estructura_examen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.curso'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='codigo_verificacion',
            field=models.UUIDField(unique=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='estructura_examen',
            field=models.JSONField(blank=True, default=dict, help_text="JSON que define la 'receta' del examen.", null=True),
        ),
        migrations.AlterField(
            model_name='preguntatema',
            name='relevancia_score',
            field=models.FloatField(default=1.0, help_text='Puntaje (0.0 a 1.0) asignado por IA sobre la relevancia.'),
        ),
        migrations.AlterField(
            model_name='preguntatema',
            name='revisado_por_agente',
            field=models.BooleanField(default=False, help_text='Marcado como True si un agente de IA ha validado esta relación.'),
        ),
    ]
