# Generated by Django 5.2.8 on 2025-12-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pregunta_curso_alter_certificado_codigo_verificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='score',
            field=models.IntegerField(default=0, help_text='Puntaje de calidad (0-30)'),
        ),
        migrations.AddField(
            model_name='curso',
            name='status',
            field=models.CharField(default='PENDIENTE', help_text='Estado de curación', max_length=20),
        ),
    ]
