# Generated by Django 5.2.4 on 2026-01-06 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_preguntatema_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_actual', models.FloatField(default=1.0)),
                ('preguntas_respondidas', models.IntegerField(default=0)),
                ('ultima_actividad', models.DateTimeField(auto_now=True)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tema')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'tema')},
            },
        ),
    ]
