# Generated by Django 5.2.4 on 2025-12-26 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pregunta_justificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsigniaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_obtenida', models.DateTimeField(auto_now_add=True)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.microcompetencia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insignias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Insignia Ganada',
                'verbose_name_plural': 'Insignias Ganadas',
                'unique_together': {('usuario', 'competencia')},
            },
        ),
    ]
