# Generated by Django 5.2.8 on 2025-12-20 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_curso_score_curso_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
