# Generated by Django 5.2.4 on 2026-01-07 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0004_perfilentrenamiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='temas',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='curso',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='verificado',
            field=models.BooleanField(default=False, help_text='Validado por IA o Humano'),
        ),
        migrations.AddField(
            model_name='tema',
            name='icono',
            field=models.CharField(default='📚', help_text='Emoji o clase FA', max_length=50),
        ),
        migrations.AlterField(
            model_name='examen',
            name='preguntas_set',
            field=models.JSONField(default=list, help_text='Lista de IDs'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='respuestas_usuario',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='microcompetencia',
            name='criterio_exito',
            field=models.TextField(help_text='Regla binaria para la IA.'),
        ),
        migrations.AlterField(
            model_name='microcompetencia',
            name='definicion_atomica',
            field=models.TextField(help_text="Define el límite exacto. Ej: 'Solo suma de celdas contiguas'."),
        ),
        migrations.AlterField(
            model_name='microcompetencia',
            name='prompt_validacion',
            field=models.TextField(blank=True, help_text='Instrucción base para evaluar esta competencia.', null=True),
        ),
        migrations.AlterField(
            model_name='microcompetencia',
            name='temas',
            field=models.ManyToManyField(help_text='Temas macro a los que pertenece esta habilidad.', related_name='competencias', to='core.tema'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_user_groups', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_user_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.DeleteModel(
            name='PreguntaTema',
        ),
    ]
