# Generated by Django 5.2.8 on 2025-12-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_curso_slug_pregunta_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='activo',
            field=models.BooleanField(default=False, verbose_name='¿Visible en Catálogo?'),
        ),
    ]
