# Generated by Django 5.2.4 on 2025-12-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_curso_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='cantidad_preguntas',
            field=models.PositiveIntegerField(default=10, verbose_name='Preguntas por Examen'),
        ),
    ]
